name: ussd_bank_codes
description: A new Flutter project. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  google_fonts: ^5.1.0
  hive: ^2.2.3
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.12
  bot_toast: ^4.0.4
  google_mobile_ads: ^3.0.0
  # google_mobile_ads: ^2.3.0
  flutter_riverpod: ^2.3.6
  internet_connection_checker_plus: ^2.0.0
  # google_mobile_ads_manager: ^1.0.1
  # admob_flutter: ^3.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: "^0.13.1"  
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  image: assets/images/app_icon.png
  color: "#FFFFFF"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

 